{
 "title": "K8SUG Karpenter Workshop Dashboard",
 "description": "Display all useful Karpenter metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(karpenter_nodepools_limit,nodepool)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "query_result(kube_deployment_created OR kube_statefulset_created)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable,instance_type)"
    }
   },
   {
    "name": "distribution_filter",
    "query": "arch,capacity_type,instance_type,namespace,node,nodepool,zone"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; padding: 20px;\">\n    <img src=\"https://kubekon.com/assets/Logo-BN_msQCs.jpg\" alt=\"K8SUG Logo\" width=\"120\" height=\"120\" style=\"margin-right: 20px;\">\n    <div>\n        <h4>Welcome to the K8SUG Karpenter Workshop Dashboard!</h4>\n        <p>Get ready to explore the powerful capabilities of Karpenter!</p>\n        <p style=\"font-size: 10px;\">Made by <a href=\"https://www.linkedin.com/in/thiago4go/\">Thiago S</a> and <a href=\"https://www.linkedin.com/in/henry-khosasih-613902119/\">Henry</a>.</p>\n        <p style=\"font-size: 10px;\">Inspired by a template published by <a href=\"https://grafana.com/grafana/dashboards/20398-karpenter/\">veleteno</a>.</p>\n    </div>\n</div>"
   }
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cluster CPU Requests",
   "type": "stat",
   "description": "Total number of cpu resources requested by all pods on the current Nodepool",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Requests",
   "type": "stat",
   "description": "Total number of memory resources requested by all pods on the current Nodepool",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node  Distribution by AZ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Distribution by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\"}) by (instance_type)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by AZ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod  Distribution by Nodepool",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\"}) by (nodepool)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Allocation",
   "type": "stat",
   "description": "Percentage of resources requested by all pods from those available on the current Nodepool nodes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"}) / sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"cpu\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Allocation",
   "type": "stat",
   "description": "Percentage of resources requested by all pods from those available on the current Nodepool nodes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"}) / sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"memory\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total number of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_allocatable{nodepool=~\"$nodepool\",resource_type=\"pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{capacity_type=\"spot\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}) or vector(0)) / count(karpenter_nodes_allocatable{instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nodepool Usage Percentage of Limit",
   "type": "timeseries",
   "description": "Percentage of how many resources Karpenter launched from the total Nodepool limit",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "karpenter_nodepools_usage{nodepool=~\"${nodepool}\", resource_type=~\"memory|cpu\"} / karpenter_nodepools_limit{nodepool=~\"${nodepool}\",resource_type=~\"memory|cpu\"} * 100",
     "legendFormat": "{{nodepool}}-{{resource_type}}"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"cpu\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"memory\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds) - sum by (node)(node_boot_time_seconds),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Node Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "increase(karpenter_nodeclaims_created_total{nodepool=~\"$nodepool\"}[5m])",
     "legendFormat": "created-\"{{nodepool}}\"-{{reason}}"
    },
    {
     "expr": "- increase(karpenter_nodeclaims_terminated_total{nodepool=~\"$nodepool\"}[5m])",
     "legendFormat": "terminated-\"{{nodepool}}\"-{{reason}}"
    }
   ]
  },
  {
   "title": "Node AZ Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"cpu\"} / karpenter_nodes_allocatable{nodepool=~\"$nodepool\",resource_type=\"cpu\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"memory\"} / karpenter_nodes_allocatable{nodepool=~\"$nodepool\", resource_type=\"memory\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "idelta(karpenter_interruption_received_messages_total[1m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Deleted Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(idelta(karpenter_interruption_deleted_messages_total[1m]))",
     "legendFormat": "Number of messages deleted"
    }
   ]
  },
  { "title": "Pods by Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\", name=~\"$application.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod  Distribution by Availability zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\",name=~\"$application.*\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod Skew By  Availability Zone",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "max(sum(karpenter_pods_state{nodepool=~\"$nodepool\", name=~\"$application.*\"}) by (zone)) - min(sum(karpenter_pods_state{nodepool=~\"$nodepool\", name=~\"$application.*\"}) by (zone))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}